source 'https://github.com/CocoaPods/Specs.git'

target 'UpdateAutoLayoutConstraints', :exclusive => true do
  pod "UpdateAutoLayoutConstraints", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UpdateAutoLayoutConstraints", :path => "../"

  
end
